// MODULES IMPORT
const express = require('express');


// CONTROLLERS IMPORT

const {
    DELETEPARKINGSPOT,
    EDITPARKINGSPOT,
    UPDATEPARKINGSPOTSTATUS,
    CREATENEWPARKINGSPOT,
    GETALLSPOTS
} = require('../controllers/ParkingSpotController');

//MIDDLEWARES IMPORT


//CREATING ROUTER
 const PARKINGSPOT = express.Router();

 //API ENDPOINTS

 //PARKING SPOT ROUTES
 PARKINGSPOT.post("/create-spot",CREATENEWPARKINGSPOT);
 PARKINGSPOT.post("/getallspots",GETALLSPOTS);
 PARKINGSPOT.patch("/edit-spot/:id",EDITPARKINGSPOT);
 PARKINGSPOT.patch("/update-status/:id",UPDATEPARKINGSPOTSTATUS);
 PARKINGSPOT.delete("/delete-spot/:id",DELETEPARKINGSPOT);

 //EXPORTING ROUTER
 module.exports = {
    PARKINGSPOTROUTER:PARKINGSPOT,
 }
 

